[build]
  publish = "dist"
  command = "npm run build:netlify"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Environment variables (set these in Netlify dashboard)
# [build.environment]
#   GMAIL_USER = "your-email@gmail.com"
#   GMAIL_APP_PASSWORD = "your-app-password"

# [context.production.environment]
#   NODE_ENV = "production"
