[build]
  publish = "dist"
  command = "npm run build:netlify"

[functions]
  directory = "netlify/functions"

# Functions are automatically served from /.netlify/functions/
# No redirects needed for functions

# Environment variables (set these in Netlify dashboard)
# [build.environment]
#   GMAIL_USER = "your-email@gmail.com"
#   GMAIL_APP_PASSWORD = "your-app-password"

# [context.production.environment]
#   NODE_ENV = "production"

# Headers for proper MIME types
[[headers]]
  for = "/*.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    Content-Disposition = "attachment"
